language: c

# Compilers to test
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev

# Command to run tests
script:
  - cmake .
  - make
  - make test

